### ISSUE TITLE
Limitation of omc describe nodes comand

### ISSUE THREAD

**Issue by oarribas** [gmeghnag/omc#66]
There is a limitation in the `omc describe nodes` command due to the content in the must-gather file.
I have opened a RFE [1] for the must-gather to include the output of `oc describe nodes`, so if that is included in the must-gather, `omc` should use it for the `omc describe nodes`.

[1] https://github.com/openshift/must-gather/issues/337

**Comment by sferich888** [comment]
`ocm describe nodes` will need to implement a veneer layer the same way `[kubectl|oc]` does, where in data is pulled from the appropriate files (from a must-gather), vs from a cluster API. 

https://github.com/kubernetes/kubectl/blob/master/pkg/describe/describe.go#L201
https://github.com/kubernetes/kubectl/blob/master/pkg/describe/describe.go#L3581-L3735

**Comment by gmeghnag** [comment]
Hi @sferich888 `omc` already has the [`describe`](https://github.com/gmeghnag/omc/blob/main/cmd/describe/core/node.go) subcommand implemented, but I think the limitations that @oarribas is speaking about are for example the resource requests and limits not shown by `omc describe node <name>` (this because the must-gather don't provide the manifests for all the pods in the cluster)

**Comment by gmeghnag** [comment]
Closing it since the needed information to implement this feature is missing from the must-gather.
